"""add users and trip ownership

Revision ID: 16a104b94ab5
Revises: d426f66146cd
Create Date: 2026-06-03 10:39:36.982868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a104b94ab5'
down_revision: Union[str, Sequence[str], None] = 'd426f66146cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('trips', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('share_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_trips_share_token'), 'trips', ['share_token'], unique=True)
    op.create_foreign_key(None, 'trips', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_share_token'), table_name='trips')
    op.drop_column('trips', 'share_token')
    op.drop_column('trips', 'owner_user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
